version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: batch-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234         # 루트 비밀번호
      MYSQL_DATABASE: sample                # 기본 DB 생성
      MYSQL_USER: admin                     # 유저 계정
      MYSQL_PASSWORD: admin                 # 유저 비밀번호
    ports:
      - "3306:3306"
    #    volumes:
    #      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    #      - mysql_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: